POST https://apinode-ubm8.onrender.com/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Primeiro Vídeo",
    "duration": 180
}

###

GET  https://apinode-ubm8.onrender.com/videos

###

PUT https://apinode-ubm8.onrender.com/videos/id
Content-Type: application/json

{
    "title": "Outro vídeo",
    "description": "Segundo Vídeo",
    "duration": 180
}

###

DELETE https://apinode-ubm8.onrender.com/videos/id
